trigger:
- master

pr:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(Build.Repository.Name)
      command: "build"
      Dockerfile: "**/Dockerfile"
      buildContext: "**"
      tags: |
        $(Build.BuildId)
        latest
  - bash: |
      ERROR_UP=$((docker-compose --file ./docker/cicd/docker-compose.yml up --force -d --build) 2>&1)
      sleep 10
      docker exec dcsl-skillmatrix-api sh -c "npm run test:report" 2>&1
      docker cp dcsl-skillmatrix-api:/usr/src/app/test-reports/junit.xml ./
      docker cp dcsl-skillmatrix-api:/usr/src/app/test-reports/coverage/lcov.info ./lcov.info
      sed -i 's|SF:/usr/src/app/|SF:|g' lcov.info

      echo "docker compose down"
      ERROR_DOWN=$((docker-compose --file ./docker/cicd/docker-compose.yml down) 2>&1)

      echo "ERROR_UP=$ERROR_UP"
      echo "ERROR_DOWN=$ERROR_DOWN"
    failOnStderr: true
    displayName: 'test: execute'

  - task: PublishTestResults@2
    displayName: 'test: publish report'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit.xml'
      failTaskOnFailedTests: true