version: '3.1'
services:
  db:
    image: postgres:10-alpine
    restart: always
    container_name: postgress-db
    environment:
      POSTGRES_PASSWORD: user
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432