version: '3.1'
services:
  db:
    ports:
      - 5432:5432
    image: postgres:12-alpine
    container_name: postgress-db-prod
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
