apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
spec:
  maxReplicas: {{ .Values.maxReplicas | default 2 }} # define max replica count
  minReplicas: {{ .Values.minReplicas | default 1 }} # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  targetCPUUtilizationPercentage: {{ .Values.cpuPercentScale | default 70 }} # target CPU utilization

